    # Tentando com o gabarito:
    version: '3'

    services:

      ghost:
        image: ghost:1-alpine
        restart: always
        ports:
          - 2368:2368
        depends_on:
          - "db"
        environment:
          # see https://ghost.org/docs/config/
          database__client: mysql
          database__connection__host: db
          database__connection__user: root
          database__connection__password: password
          database__connection__database: ghost
        networks:
          - my-network

      db:
        # platform: linux/x86_64 # Caso utilize MacOS, descomente essa linha
        image: mysql:5.7
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: password
        volumes:
          - db-data:/var/lib/mysql
        networks:
          - my-network

    volumes:
      db-data:

    networks:
      my-network:

# Starts with: docker-compose up -d