FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "./seu-arquivo.py" ]

# Também é possível utilizar os comandos abaixo para criar/executar um container com python

# Baixe a última versão do python
# docker pull python

# Execute o REPL a partir da imagem baixada
# docker run -it --rm python:tag