version: '3'
services:
  ghostBlog:
    image: ghost:1-alpine # usa-se image em vez de build, pois não será realizada nenhuma alteração. Apenas usaremos a imagem-base pronta
    ports:
      - 2368:2368

# Starts with: docker-compose up
# See on: 'http://localhost:2368'
# Stops with: docker-compose down